/**
 *
 * @file dag_colors.h
 *
 * @copyright 2009-2014 The University of Tennessee and The University of
 *                      Tennessee Research Foundation. All rights reserved.
 * @copyright 2012-2026 Bordeaux INP, CNRS (LaBRI UMR 5800), Inria,
 *                      Univ. Bordeaux. All rights reserved.
 *
 ***
 *
 * @brief Chameleon DAG color defaults
 *
 * @version 1.4.0
 * @author Mathieu Faverge
 * @date 2026-08-01
 *
 */
#ifndef _chameleon_dag_colors_h_
#define _chameleon_dag_colors_h_

/* StarPU consumes 0xRRGGBB values, while Quark consumes the matching strings. */
#define CHAMELEON_DAG_COLOR_BLAS1      0x8ecae6
#define CHAMELEON_DAG_COLOR_BLAS2      0x219ebc
#define CHAMELEON_DAG_COLOR_GEMM       0xffc857
#define CHAMELEON_DAG_COLOR_HEMM       0x277da1
#define CHAMELEON_DAG_COLOR_SYMM       0x90be6d
#define CHAMELEON_DAG_COLOR_HER2K      0xf9844a
#define CHAMELEON_DAG_COLOR_HERK       0xf4a261
#define CHAMELEON_DAG_COLOR_SYR2K      0xf9c74f
#define CHAMELEON_DAG_COLOR_SYRK       0xe9c46a
#define CHAMELEON_DAG_COLOR_TRMM       0x2a9d8f
#define CHAMELEON_DAG_COLOR_TRSM       0x118ab2
#define CHAMELEON_DAG_COLOR_FACTO      0x43aa8b
#define CHAMELEON_DAG_COLOR_LU         0x577590
#define CHAMELEON_DAG_COLOR_QR         0xf3722c
#define CHAMELEON_DAG_COLOR_APPLYQ     0xf8961e
#define CHAMELEON_DAG_COLOR_GENERATEQ  0xff6b35
#define CHAMELEON_DAG_COLOR_BAND       0xb56576
#define CHAMELEON_DAG_COLOR_PERM       0xf94144
#define CHAMELEON_DAG_COLOR_COPY       0xadb5bd
#define CHAMELEON_DAG_COLOR_NORM       0x4d908e
#define CHAMELEON_DAG_COLOR_RANDOM     0x9b5de5
#define CHAMELEON_DAG_COLOR_ANALYSIS   0x00bbf9
#define CHAMELEON_DAG_COLOR_MISC       0xffffff

#define CHAMELEON_DAG_COLOR_BLAS1_STR      "#8ecae6"
#define CHAMELEON_DAG_COLOR_BLAS2_STR      "#219ebc"
#define CHAMELEON_DAG_COLOR_GEMM_STR       "#ffc857"
#define CHAMELEON_DAG_COLOR_HEMM_STR       "#277da1"
#define CHAMELEON_DAG_COLOR_SYMM_STR       "#90be6d"
#define CHAMELEON_DAG_COLOR_HER2K_STR      "#f9844a"
#define CHAMELEON_DAG_COLOR_HERK_STR       "#f4a261"
#define CHAMELEON_DAG_COLOR_SYR2K_STR      "#f9c74f"
#define CHAMELEON_DAG_COLOR_SYRK_STR       "#e9c46a"
#define CHAMELEON_DAG_COLOR_TRMM_STR       "#2a9d8f"
#define CHAMELEON_DAG_COLOR_TRSM_STR       "#118ab2"
#define CHAMELEON_DAG_COLOR_FACTO_STR      "#43aa8b"
#define CHAMELEON_DAG_COLOR_LU_STR         "#577590"
#define CHAMELEON_DAG_COLOR_QR_STR         "#f3722c"
#define CHAMELEON_DAG_COLOR_APPLYQ_STR     "#f8961e"
#define CHAMELEON_DAG_COLOR_GENERATEQ_STR  "#ff6b35"
#define CHAMELEON_DAG_COLOR_BAND_STR       "#b56576"
#define CHAMELEON_DAG_COLOR_PERM_STR       "#f94144"
#define CHAMELEON_DAG_COLOR_COPY_STR       "#adb5bd"
#define CHAMELEON_DAG_COLOR_NORM_STR       "#4d908e"
#define CHAMELEON_DAG_COLOR_RANDOM_STR     "#9b5de5"
#define CHAMELEON_DAG_COLOR_ANALYSIS_STR   "#00bbf9"
#define CHAMELEON_DAG_COLOR_MISC_STR       "#ffffff"

static inline const char *
chameleon_dag_color_to_string( int color )
{
    switch( color ) {
    case CHAMELEON_DAG_COLOR_BLAS1:
        return CHAMELEON_DAG_COLOR_BLAS1_STR;
    case CHAMELEON_DAG_COLOR_BLAS2:
        return CHAMELEON_DAG_COLOR_BLAS2_STR;
    case CHAMELEON_DAG_COLOR_GEMM:
        return CHAMELEON_DAG_COLOR_GEMM_STR;
    case CHAMELEON_DAG_COLOR_HEMM:
        return CHAMELEON_DAG_COLOR_HEMM_STR;
    case CHAMELEON_DAG_COLOR_SYMM:
        return CHAMELEON_DAG_COLOR_SYMM_STR;
    case CHAMELEON_DAG_COLOR_HER2K:
        return CHAMELEON_DAG_COLOR_HER2K_STR;
    case CHAMELEON_DAG_COLOR_HERK:
        return CHAMELEON_DAG_COLOR_HERK_STR;
    case CHAMELEON_DAG_COLOR_SYR2K:
        return CHAMELEON_DAG_COLOR_SYR2K_STR;
    case CHAMELEON_DAG_COLOR_SYRK:
        return CHAMELEON_DAG_COLOR_SYRK_STR;
    case CHAMELEON_DAG_COLOR_TRMM:
        return CHAMELEON_DAG_COLOR_TRMM_STR;
    case CHAMELEON_DAG_COLOR_TRSM:
        return CHAMELEON_DAG_COLOR_TRSM_STR;
    case CHAMELEON_DAG_COLOR_FACTO:
        return CHAMELEON_DAG_COLOR_FACTO_STR;
    case CHAMELEON_DAG_COLOR_LU:
        return CHAMELEON_DAG_COLOR_LU_STR;
    case CHAMELEON_DAG_COLOR_QR:
        return CHAMELEON_DAG_COLOR_QR_STR;
    case CHAMELEON_DAG_COLOR_APPLYQ:
        return CHAMELEON_DAG_COLOR_APPLYQ_STR;
    case CHAMELEON_DAG_COLOR_GENERATEQ:
        return CHAMELEON_DAG_COLOR_GENERATEQ_STR;
    case CHAMELEON_DAG_COLOR_BAND:
        return CHAMELEON_DAG_COLOR_BAND_STR;
    case CHAMELEON_DAG_COLOR_PERM:
        return CHAMELEON_DAG_COLOR_PERM_STR;
    case CHAMELEON_DAG_COLOR_COPY:
        return CHAMELEON_DAG_COLOR_COPY_STR;
    case CHAMELEON_DAG_COLOR_NORM:
        return CHAMELEON_DAG_COLOR_NORM_STR;
    case CHAMELEON_DAG_COLOR_RANDOM:
        return CHAMELEON_DAG_COLOR_RANDOM_STR;
    case CHAMELEON_DAG_COLOR_ANALYSIS:
        return CHAMELEON_DAG_COLOR_ANALYSIS_STR;
    default:
        return CHAMELEON_DAG_COLOR_MISC_STR;
    }
}

#define CHAMELEON_DAG_COLOR_TO_STR(_color_) \
    chameleon_dag_color_to_string( _color_ )

/*
 * The runtime mode test is emitted only in color-enabled builds. Otherwise,
 * callers that still generate a DAG use the compile-time task color directly.
 */
#if defined(CHAMELEON_ENABLE_DAG_COLORS)
#define CHAMELEON_DAG_TASK_GET_COLOR(_options_, _name_) \
    ( ((_options_)->dag_color_mode == ChamDagColorTask) ?         \
      CHAMELEON_DAG_TASK_COLOR( _name_ ) : (_options_)->taskcolor )
#else
#define CHAMELEON_DAG_TASK_GET_COLOR(_options_, _name_) \
    CHAMELEON_DAG_TASK_COLOR( _name_ )
#endif

#define CHAMELEON_DAG_TASK_GET_COLOR_STR(_options_, _name_) \
    CHAMELEON_DAG_COLOR_TO_STR( CHAMELEON_DAG_TASK_GET_COLOR( (_options_), _name_ ) )

/* Default color assigned to every task submitted by a high-level algorithm. */
#define CHAMELEON_DAG_COLOR_ALGORITHM(_name_) CHAMELEON_DAG_ALG_COLOR_##_name_

#define CHAMELEON_DAG_ALG_COLOR_bcast        CHAMELEON_DAG_COLOR_MISC
#define CHAMELEON_DAG_ALG_COLOR_cesca        CHAMELEON_DAG_COLOR_ANALYSIS
#define CHAMELEON_DAG_ALG_COLOR_gebrd        CHAMELEON_DAG_COLOR_BAND
#define CHAMELEON_DAG_ALG_COLOR_gelqf        CHAMELEON_DAG_COLOR_QR
#define CHAMELEON_DAG_ALG_COLOR_gelqf_param  CHAMELEON_DAG_COLOR_QR
#define CHAMELEON_DAG_ALG_COLOR_gelqfrh      CHAMELEON_DAG_COLOR_QR
#define CHAMELEON_DAG_ALG_COLOR_gemm         CHAMELEON_DAG_COLOR_GEMM
#define CHAMELEON_DAG_ALG_COLOR_genm2        CHAMELEON_DAG_COLOR_RANDOM
#define CHAMELEON_DAG_ALG_COLOR_gepdf_qdwh   CHAMELEON_DAG_COLOR_ANALYSIS
#define CHAMELEON_DAG_ALG_COLOR_gepdf_qr     CHAMELEON_DAG_COLOR_ANALYSIS
#define CHAMELEON_DAG_ALG_COLOR_geqrf        CHAMELEON_DAG_COLOR_QR
#define CHAMELEON_DAG_ALG_COLOR_geqrf_param  CHAMELEON_DAG_COLOR_QR
#define CHAMELEON_DAG_ALG_COLOR_geqrfrh      CHAMELEON_DAG_COLOR_QR
#define CHAMELEON_DAG_ALG_COLOR_gered        CHAMELEON_DAG_COLOR_ANALYSIS
#define CHAMELEON_DAG_ALG_COLOR_gerst        CHAMELEON_DAG_COLOR_ANALYSIS
#define CHAMELEON_DAG_ALG_COLOR_getrf        CHAMELEON_DAG_COLOR_LU
#define CHAMELEON_DAG_ALG_COLOR_getrf_incpiv CHAMELEON_DAG_COLOR_LU
#define CHAMELEON_DAG_ALG_COLOR_getrf_nopiv  CHAMELEON_DAG_COLOR_LU
#define CHAMELEON_DAG_ALG_COLOR_gram         CHAMELEON_DAG_COLOR_ANALYSIS
#define CHAMELEON_DAG_ALG_COLOR_hemm         CHAMELEON_DAG_COLOR_HEMM
#define CHAMELEON_DAG_ALG_COLOR_her2k        CHAMELEON_DAG_COLOR_HER2K
#define CHAMELEON_DAG_ALG_COLOR_hered        CHAMELEON_DAG_COLOR_BAND
#define CHAMELEON_DAG_ALG_COLOR_herk         CHAMELEON_DAG_COLOR_HERK
#define CHAMELEON_DAG_ALG_COLOR_hetrd_he2hb  CHAMELEON_DAG_COLOR_BAND
#define CHAMELEON_DAG_ALG_COLOR_hetrd_sy2sb  CHAMELEON_DAG_COLOR_BAND
#define CHAMELEON_DAG_ALG_COLOR_lacpy        CHAMELEON_DAG_COLOR_COPY
#define CHAMELEON_DAG_ALG_COLOR_lag2c        CHAMELEON_DAG_COLOR_COPY
#define CHAMELEON_DAG_ALG_COLOR_lange        CHAMELEON_DAG_COLOR_NORM
#define CHAMELEON_DAG_ALG_COLOR_lansy        CHAMELEON_DAG_COLOR_NORM
#define CHAMELEON_DAG_ALG_COLOR_lascal       CHAMELEON_DAG_COLOR_BLAS1
#define CHAMELEON_DAG_ALG_COLOR_laset        CHAMELEON_DAG_COLOR_COPY
#define CHAMELEON_DAG_ALG_COLOR_laset2       CHAMELEON_DAG_COLOR_COPY
#define CHAMELEON_DAG_ALG_COLOR_laswp        CHAMELEON_DAG_COLOR_PERM
#define CHAMELEON_DAG_ALG_COLOR_laswpc       CHAMELEON_DAG_COLOR_PERM
#define CHAMELEON_DAG_ALG_COLOR_latms        CHAMELEON_DAG_COLOR_RANDOM
#define CHAMELEON_DAG_ALG_COLOR_latro        CHAMELEON_DAG_COLOR_COPY
#define CHAMELEON_DAG_ALG_COLOR_lauum        CHAMELEON_DAG_COLOR_FACTO
#define CHAMELEON_DAG_ALG_COLOR_map          CHAMELEON_DAG_COLOR_MISC
#define CHAMELEON_DAG_ALG_COLOR_plghe        CHAMELEON_DAG_COLOR_RANDOM
#define CHAMELEON_DAG_ALG_COLOR_plgsy        CHAMELEON_DAG_COLOR_RANDOM
#define CHAMELEON_DAG_ALG_COLOR_plrnk        CHAMELEON_DAG_COLOR_RANDOM
#define CHAMELEON_DAG_ALG_COLOR_plrnt        CHAMELEON_DAG_COLOR_RANDOM
#define CHAMELEON_DAG_ALG_COLOR_potrf        CHAMELEON_DAG_COLOR_FACTO
#define CHAMELEON_DAG_ALG_COLOR_potrimm      CHAMELEON_DAG_COLOR_FACTO
#define CHAMELEON_DAG_ALG_COLOR_symm         CHAMELEON_DAG_COLOR_SYMM
#define CHAMELEON_DAG_ALG_COLOR_syr2k        CHAMELEON_DAG_COLOR_SYR2K
#define CHAMELEON_DAG_ALG_COLOR_syrk         CHAMELEON_DAG_COLOR_SYRK
#define CHAMELEON_DAG_ALG_COLOR_sytrf        CHAMELEON_DAG_COLOR_LU
#define CHAMELEON_DAG_ALG_COLOR_tile2band    CHAMELEON_DAG_COLOR_BAND
#define CHAMELEON_DAG_ALG_COLOR_tpgqrt       CHAMELEON_DAG_COLOR_QR
#define CHAMELEON_DAG_ALG_COLOR_tpgqrt_param CHAMELEON_DAG_COLOR_QR
#define CHAMELEON_DAG_ALG_COLOR_tpqrt        CHAMELEON_DAG_COLOR_QR
#define CHAMELEON_DAG_ALG_COLOR_tpqrt_param  CHAMELEON_DAG_COLOR_QR
#define CHAMELEON_DAG_ALG_COLOR_tradd        CHAMELEON_DAG_COLOR_BLAS1
#define CHAMELEON_DAG_ALG_COLOR_trmm         CHAMELEON_DAG_COLOR_TRMM
#define CHAMELEON_DAG_ALG_COLOR_trsm         CHAMELEON_DAG_COLOR_TRSM
#define CHAMELEON_DAG_ALG_COLOR_trsmpl       CHAMELEON_DAG_COLOR_LU
#define CHAMELEON_DAG_ALG_COLOR_trtri        CHAMELEON_DAG_COLOR_FACTO
#define CHAMELEON_DAG_ALG_COLOR_unglq        CHAMELEON_DAG_COLOR_GENERATEQ
#define CHAMELEON_DAG_ALG_COLOR_unglq_param  CHAMELEON_DAG_COLOR_GENERATEQ
#define CHAMELEON_DAG_ALG_COLOR_unglqrh      CHAMELEON_DAG_COLOR_GENERATEQ
#define CHAMELEON_DAG_ALG_COLOR_ungqr        CHAMELEON_DAG_COLOR_GENERATEQ
#define CHAMELEON_DAG_ALG_COLOR_ungqr_param  CHAMELEON_DAG_COLOR_GENERATEQ
#define CHAMELEON_DAG_ALG_COLOR_ungqrrh      CHAMELEON_DAG_COLOR_GENERATEQ
#define CHAMELEON_DAG_ALG_COLOR_unmlq        CHAMELEON_DAG_COLOR_APPLYQ
#define CHAMELEON_DAG_ALG_COLOR_unmlq_param  CHAMELEON_DAG_COLOR_APPLYQ
#define CHAMELEON_DAG_ALG_COLOR_unmlqrh      CHAMELEON_DAG_COLOR_APPLYQ
#define CHAMELEON_DAG_ALG_COLOR_unmqr        CHAMELEON_DAG_COLOR_APPLYQ
#define CHAMELEON_DAG_ALG_COLOR_unmqr_param  CHAMELEON_DAG_COLOR_APPLYQ
#define CHAMELEON_DAG_ALG_COLOR_unmqrrh      CHAMELEON_DAG_COLOR_APPLYQ

#endif /* _chameleon_dag_colors_h_ */
