/**
 *
 * @file dag_task_colors.h
 *
 * @copyright 2009-2014 The University of Tennessee and The University of
 *                      Tennessee Research Foundation. All rights reserved.
 * @copyright 2012-2026 Bordeaux INP, CNRS (LaBRI UMR 5800), Inria,
 *                      Univ. Bordeaux. All rights reserved.
 *
 ***
 *
 * @brief Chameleon DAG task color defaults
 *
 * @version 1.4.0
 * @author Mathieu Faverge
 * @date 2026-08-01
 *
 */
#ifndef _chameleon_dag_task_colors_h_
#define _chameleon_dag_task_colors_h_

#include "control/dag_colors.h"

/* Two expansion levels are required before concatenating a task class. */
#define CHAMELEON_DAG_TASK_COLOR(_name_)  CHAMELEON_DAG_TASK_COLOR_EXPAND( _name_ )
#define CHAMELEON_DAG_TASK_COLOR_EXPAND(_name_) CHAMELEON_DAG_TASK_COLOR_##_name_

/*
 * StarPU insertion macros receive precision-qualified codelet names. Map them
 * to precision-neutral task classes shared with Quark before selecting colors.
 * Keep this list synchronized with names passed to the StarPU common task and
 * common parameter macros, including names produced by precision generation.
 */
#define CHAMELEON_DAG_TASK_COLOR_NAME(_name_) \
    CHAMELEON_DAG_TASK_COLOR_NAME_EXPAND( _name_ )
#define CHAMELEON_DAG_TASK_COLOR_NAME_EXPAND(_name_) \
    CHAMELEON_DAG_TASK_COLOR_NAME_##_name_

#define CHAMELEON_DAG_TASK_COLOR_NAME_caddi                                    ADDI
#define CHAMELEON_DAG_TASK_COLOR_NAME_caxpy                                    AXPY
#define CHAMELEON_DAG_TASK_COLOR_NAME_ccesca                                   CESCA
#define CHAMELEON_DAG_TASK_COLOR_NAME_cgeadd                                   GEADD
#define CHAMELEON_DAG_TASK_COLOR_NAME_cgelqt                                   GELQT
#define CHAMELEON_DAG_TASK_COLOR_NAME_cgemm                                    GEMM
#define CHAMELEON_DAG_TASK_COLOR_NAME_cgemv                                    GEMV
#define CHAMELEON_DAG_TASK_COLOR_NAME_cgeqrt                                   GEQRT
#define CHAMELEON_DAG_TASK_COLOR_NAME_cgessm                                   GESSM
#define CHAMELEON_DAG_TASK_COLOR_NAME_cgessq                                   GESSQ
#define CHAMELEON_DAG_TASK_COLOR_NAME_cgesum                                   GESUM
#define CHAMELEON_DAG_TASK_COLOR_NAME_cgetrf                                   GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_cgetrf_blocked_diag                      GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_cgetrf_blocked_offdiag                   GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_cgetrf_blocked_trsm                      GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_cgetrf_cpy_pivrow_in_Up                  GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_cgetrf_incpiv                            GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_cgetrf_nopiv                             GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_cgetrf_nopiv_percol_diag                 GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_cgetrf_nopiv_percol_trsm                 GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_cgetrf_panel_blocked_batched             GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_cgetrf_panel_offdiag_batched             GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_cgetrf_panel_percol_offdiag_batched      GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_cgetrf_percol_diag                       GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_cgetrf_percol_offdiag                    GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_cgram                                    GRAM
#define CHAMELEON_DAG_TASK_COLOR_NAME_che2ge                                   HE2GE
#define CHAMELEON_DAG_TASK_COLOR_NAME_chemm                                    HEMM
#define CHAMELEON_DAG_TASK_COLOR_NAME_cher2k                                   HER2K
#define CHAMELEON_DAG_TASK_COLOR_NAME_cherfb                                   HERFB
#define CHAMELEON_DAG_TASK_COLOR_NAME_cherk                                    HERK
#define CHAMELEON_DAG_TASK_COLOR_NAME_chetrrk                                  HETRRK
#define CHAMELEON_DAG_TASK_COLOR_NAME_cipiv_allreduce                          PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_cipiv_allreduce_recv                     PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_cipiv_allreduce_send                     PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_clacpy                                   LACPY
#define CHAMELEON_DAG_TASK_COLOR_NAME_clacpyx                                  LACPY
#define CHAMELEON_DAG_TASK_COLOR_NAME_clag2z                                   LAG2Z
#define CHAMELEON_DAG_TASK_COLOR_NAME_clange                                   LANGE
#define CHAMELEON_DAG_TASK_COLOR_NAME_clange_max                               LANGE_MAX
#define CHAMELEON_DAG_TASK_COLOR_NAME_clascal                                  LASCAL
#define CHAMELEON_DAG_TASK_COLOR_NAME_claset                                   LASET
#define CHAMELEON_DAG_TASK_COLOR_NAME_claset2                                  LASET
#define CHAMELEON_DAG_TASK_COLOR_NAME_claswp_batched                           LASWP
#define CHAMELEON_DAG_TASK_COLOR_NAME_claswp_gemm                              LASWP
#define CHAMELEON_DAG_TASK_COLOR_NAME_claswp_get                               LASWP
#define CHAMELEON_DAG_TASK_COLOR_NAME_claswp_get_batched                       LASWP
#define CHAMELEON_DAG_TASK_COLOR_NAME_claswp_ret                               LASWP
#define CHAMELEON_DAG_TASK_COLOR_NAME_claswp_set                               LASWP
#define CHAMELEON_DAG_TASK_COLOR_NAME_claswp_set_batched                       LASWP
#define CHAMELEON_DAG_TASK_COLOR_NAME_clatro                                   LATRO
#define CHAMELEON_DAG_TASK_COLOR_NAME_clauum                                   LAUUM
#define CHAMELEON_DAG_TASK_COLOR_NAME_clumm                                    LUMM
#define CHAMELEON_DAG_TASK_COLOR_NAME_convert                                  CONVERT
#define CHAMELEON_DAG_TASK_COLOR_NAME_cperm_allreduce                          PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_cperm_allreduce_col                      PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_cperm_allreduce_init                     PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_cperm_allreduce_send_col                 PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_cperm_reduce                             PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_cperm_reduce_col                         PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_cperm_reduce_col_send                    PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_cperm_reduce_init                        PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_cperm_reduce_send                        PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_cpivot_allreduce                         PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_cpivot_allreduce_recv                    PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_cpivot_allreduce_send                    PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_cplghe                                   PLGHE
#define CHAMELEON_DAG_TASK_COLOR_NAME_cplgsy                                   PLGSY
#define CHAMELEON_DAG_TASK_COLOR_NAME_cplrnt                                   PLRNT
#define CHAMELEON_DAG_TASK_COLOR_NAME_cplssq                                   PLSSQ
#define CHAMELEON_DAG_TASK_COLOR_NAME_cplssq2                                  PLSSQ2
#define CHAMELEON_DAG_TASK_COLOR_NAME_cpotrf                                   POTRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_cset_reciprocal_diagonal                 SET_RECIPROCAL_DIAGONAL
#define CHAMELEON_DAG_TASK_COLOR_NAME_cssssm                                   SSSSM
#define CHAMELEON_DAG_TASK_COLOR_NAME_csymm                                    SYMM
#define CHAMELEON_DAG_TASK_COLOR_NAME_csyr2k                                   SYR2K
#define CHAMELEON_DAG_TASK_COLOR_NAME_csyrk                                    SYRK
#define CHAMELEON_DAG_TASK_COLOR_NAME_csytrf_nopiv                             SYTRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_csytrrk                                  SYTRRK
#define CHAMELEON_DAG_TASK_COLOR_NAME_ctplqt                                   TPLQT
#define CHAMELEON_DAG_TASK_COLOR_NAME_ctpmlqt                                  TPMLQT
#define CHAMELEON_DAG_TASK_COLOR_NAME_ctpmqrt                                  TPMQRT
#define CHAMELEON_DAG_TASK_COLOR_NAME_ctpqrt                                   TPQRT
#define CHAMELEON_DAG_TASK_COLOR_NAME_ctradd                                   TRADD
#define CHAMELEON_DAG_TASK_COLOR_NAME_ctrasm                                   TRASM
#define CHAMELEON_DAG_TASK_COLOR_NAME_ctrmm                                    TRMM
#define CHAMELEON_DAG_TASK_COLOR_NAME_ctrmmoop                                 TRMM
#define CHAMELEON_DAG_TASK_COLOR_NAME_ctrsm                                    TRSM
#define CHAMELEON_DAG_TASK_COLOR_NAME_ctrtri                                   TRTRI
#define CHAMELEON_DAG_TASK_COLOR_NAME_ctrtrmm                                  TRTRMM
#define CHAMELEON_DAG_TASK_COLOR_NAME_ctrtrsm                                  TRTRSM
#define CHAMELEON_DAG_TASK_COLOR_NAME_ctsmlq_hetra1                            TSMLQ
#define CHAMELEON_DAG_TASK_COLOR_NAME_ctsmqr_hetra1                            TSMQR
#define CHAMELEON_DAG_TASK_COLOR_NAME_ctstrf                                   TSTRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_cunmlq                                   UNMLQ
#define CHAMELEON_DAG_TASK_COLOR_NAME_cunmqr                                   UNMQR
#define CHAMELEON_DAG_TASK_COLOR_NAME_daddi                                    ADDI
#define CHAMELEON_DAG_TASK_COLOR_NAME_dasum                                    ASUM
#define CHAMELEON_DAG_TASK_COLOR_NAME_daxpy                                    AXPY
#define CHAMELEON_DAG_TASK_COLOR_NAME_dcesca                                   CESCA
#define CHAMELEON_DAG_TASK_COLOR_NAME_dgeadd                                   GEADD
#define CHAMELEON_DAG_TASK_COLOR_NAME_dgelqt                                   GELQT
#define CHAMELEON_DAG_TASK_COLOR_NAME_dgemm                                    GEMM
#define CHAMELEON_DAG_TASK_COLOR_NAME_dgemv                                    GEMV
#define CHAMELEON_DAG_TASK_COLOR_NAME_dgeqrt                                   GEQRT
#define CHAMELEON_DAG_TASK_COLOR_NAME_dgessm                                   GESSM
#define CHAMELEON_DAG_TASK_COLOR_NAME_dgessq                                   GESSQ
#define CHAMELEON_DAG_TASK_COLOR_NAME_dgesum                                   GESUM
#define CHAMELEON_DAG_TASK_COLOR_NAME_dgetrf                                   GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_dgetrf_blocked_diag                      GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_dgetrf_blocked_offdiag                   GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_dgetrf_blocked_trsm                      GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_dgetrf_cpy_pivrow_in_Up                  GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_dgetrf_incpiv                            GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_dgetrf_nopiv                             GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_dgetrf_nopiv_percol_diag                 GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_dgetrf_nopiv_percol_trsm                 GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_dgetrf_panel_blocked_batched             GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_dgetrf_panel_offdiag_batched             GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_dgetrf_panel_percol_offdiag_batched      GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_dgetrf_percol_diag                       GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_dgetrf_percol_offdiag                    GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_dgram                                    GRAM
#define CHAMELEON_DAG_TASK_COLOR_NAME_dhe2ge                                   HE2GE
#define CHAMELEON_DAG_TASK_COLOR_NAME_dipiv_allreduce                          PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_dipiv_allreduce_recv                     PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_dipiv_allreduce_send                     PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_dlacpy                                   LACPY
#define CHAMELEON_DAG_TASK_COLOR_NAME_dlacpyx                                  LACPY
#define CHAMELEON_DAG_TASK_COLOR_NAME_dlag2h                                   LAG2H
#define CHAMELEON_DAG_TASK_COLOR_NAME_dlag2s                                   LAG2S
#define CHAMELEON_DAG_TASK_COLOR_NAME_dlag2z                                   LAG2Z
#define CHAMELEON_DAG_TASK_COLOR_NAME_dlange                                   LANGE
#define CHAMELEON_DAG_TASK_COLOR_NAME_dlange_max                               LANGE_MAX
#define CHAMELEON_DAG_TASK_COLOR_NAME_dlascal                                  LASCAL
#define CHAMELEON_DAG_TASK_COLOR_NAME_dlaset                                   LASET
#define CHAMELEON_DAG_TASK_COLOR_NAME_dlaset2                                  LASET
#define CHAMELEON_DAG_TASK_COLOR_NAME_dlaswp_batched                           LASWP
#define CHAMELEON_DAG_TASK_COLOR_NAME_dlaswp_gemm                              LASWP
#define CHAMELEON_DAG_TASK_COLOR_NAME_dlaswp_get                               LASWP
#define CHAMELEON_DAG_TASK_COLOR_NAME_dlaswp_get_batched                       LASWP
#define CHAMELEON_DAG_TASK_COLOR_NAME_dlaswp_ret                               LASWP
#define CHAMELEON_DAG_TASK_COLOR_NAME_dlaswp_set                               LASWP
#define CHAMELEON_DAG_TASK_COLOR_NAME_dlaswp_set_batched                       LASWP
#define CHAMELEON_DAG_TASK_COLOR_NAME_dlatro                                   LATRO
#define CHAMELEON_DAG_TASK_COLOR_NAME_dlauum                                   LAUUM
#define CHAMELEON_DAG_TASK_COLOR_NAME_dlumm                                    LUMM
#define CHAMELEON_DAG_TASK_COLOR_NAME_dormlq                                   ORMLQ
#define CHAMELEON_DAG_TASK_COLOR_NAME_dormqr                                   ORMQR
#define CHAMELEON_DAG_TASK_COLOR_NAME_dperm_allreduce                          PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_dperm_allreduce_col                      PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_dperm_allreduce_init                     PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_dperm_allreduce_send_col                 PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_dperm_reduce                             PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_dperm_reduce_col                         PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_dperm_reduce_col_send                    PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_dperm_reduce_init                        PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_dperm_reduce_send                        PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_dpivot_allreduce                         PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_dpivot_allreduce_recv                    PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_dpivot_allreduce_send                    PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_dplgsy                                   PLGSY
#define CHAMELEON_DAG_TASK_COLOR_NAME_dplrnt                                   PLRNT
#define CHAMELEON_DAG_TASK_COLOR_NAME_dplssq                                   PLSSQ
#define CHAMELEON_DAG_TASK_COLOR_NAME_dplssq2                                  PLSSQ2
#define CHAMELEON_DAG_TASK_COLOR_NAME_dpotrf                                   POTRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_dset_reciprocal_diagonal                 SET_RECIPROCAL_DIAGONAL
#define CHAMELEON_DAG_TASK_COLOR_NAME_dssssm                                   SSSSM
#define CHAMELEON_DAG_TASK_COLOR_NAME_dsymm                                    SYMM
#define CHAMELEON_DAG_TASK_COLOR_NAME_dsyr2k                                   SYR2K
#define CHAMELEON_DAG_TASK_COLOR_NAME_dsyrfb                                   SYRFB
#define CHAMELEON_DAG_TASK_COLOR_NAME_dsyrk                                    SYRK
#define CHAMELEON_DAG_TASK_COLOR_NAME_dsytrrk                                  SYTRRK
#define CHAMELEON_DAG_TASK_COLOR_NAME_dtplqt                                   TPLQT
#define CHAMELEON_DAG_TASK_COLOR_NAME_dtpmlqt                                  TPMLQT
#define CHAMELEON_DAG_TASK_COLOR_NAME_dtpmqrt                                  TPMQRT
#define CHAMELEON_DAG_TASK_COLOR_NAME_dtpqrt                                   TPQRT
#define CHAMELEON_DAG_TASK_COLOR_NAME_dtradd                                   TRADD
#define CHAMELEON_DAG_TASK_COLOR_NAME_dtrasm                                   TRASM
#define CHAMELEON_DAG_TASK_COLOR_NAME_dtrmm                                    TRMM
#define CHAMELEON_DAG_TASK_COLOR_NAME_dtrmmoop                                 TRMM
#define CHAMELEON_DAG_TASK_COLOR_NAME_dtrsm                                    TRSM
#define CHAMELEON_DAG_TASK_COLOR_NAME_dtrtri                                   TRTRI
#define CHAMELEON_DAG_TASK_COLOR_NAME_dtrtrmm                                  TRTRMM
#define CHAMELEON_DAG_TASK_COLOR_NAME_dtrtrsm                                  TRTRSM
#define CHAMELEON_DAG_TASK_COLOR_NAME_dtsmlq_hetra1                            TSMLQ
#define CHAMELEON_DAG_TASK_COLOR_NAME_dtsmqr_hetra1                            TSMQR
#define CHAMELEON_DAG_TASK_COLOR_NAME_dtstrf                                   TSTRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_dzasum                                   ASUM
#define CHAMELEON_DAG_TASK_COLOR_NAME_gemm                                     GEMM
#define CHAMELEON_DAG_TASK_COLOR_NAME_gemmex                                   GEMM
#define CHAMELEON_DAG_TASK_COLOR_NAME_hgemm                                    GEMM
#define CHAMELEON_DAG_TASK_COLOR_NAME_hlag2d                                   LAG2D
#define CHAMELEON_DAG_TASK_COLOR_NAME_hlag2s                                   LAG2S
#define CHAMELEON_DAG_TASK_COLOR_NAME_ipiv_to_perm                             PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_map                                      MAP
#define CHAMELEON_DAG_TASK_COLOR_NAME_map_one                                  MAP
#define CHAMELEON_DAG_TASK_COLOR_NAME_map_three                                MAP
#define CHAMELEON_DAG_TASK_COLOR_NAME_map_two                                  MAP
#define CHAMELEON_DAG_TASK_COLOR_NAME_saddi                                    ADDI
#define CHAMELEON_DAG_TASK_COLOR_NAME_sasum                                    ASUM
#define CHAMELEON_DAG_TASK_COLOR_NAME_saxpy                                    AXPY
#define CHAMELEON_DAG_TASK_COLOR_NAME_scasum                                   ASUM
#define CHAMELEON_DAG_TASK_COLOR_NAME_scesca                                   CESCA
#define CHAMELEON_DAG_TASK_COLOR_NAME_sgeadd                                   GEADD
#define CHAMELEON_DAG_TASK_COLOR_NAME_sgelqt                                   GELQT
#define CHAMELEON_DAG_TASK_COLOR_NAME_sgemm                                    GEMM
#define CHAMELEON_DAG_TASK_COLOR_NAME_sgemv                                    GEMV
#define CHAMELEON_DAG_TASK_COLOR_NAME_sgeqrt                                   GEQRT
#define CHAMELEON_DAG_TASK_COLOR_NAME_sgessm                                   GESSM
#define CHAMELEON_DAG_TASK_COLOR_NAME_sgessq                                   GESSQ
#define CHAMELEON_DAG_TASK_COLOR_NAME_sgesum                                   GESUM
#define CHAMELEON_DAG_TASK_COLOR_NAME_sgetrf                                   GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_sgetrf_blocked_diag                      GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_sgetrf_blocked_offdiag                   GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_sgetrf_blocked_trsm                      GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_sgetrf_cpy_pivrow_in_Up                  GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_sgetrf_incpiv                            GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_sgetrf_nopiv                             GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_sgetrf_nopiv_percol_diag                 GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_sgetrf_nopiv_percol_trsm                 GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_sgetrf_panel_blocked_batched             GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_sgetrf_panel_offdiag_batched             GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_sgetrf_panel_percol_offdiag_batched      GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_sgetrf_percol_diag                       GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_sgetrf_percol_offdiag                    GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_sgram                                    GRAM
#define CHAMELEON_DAG_TASK_COLOR_NAME_she2ge                                   HE2GE
#define CHAMELEON_DAG_TASK_COLOR_NAME_sipiv_allreduce                          PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_sipiv_allreduce_recv                     PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_sipiv_allreduce_send                     PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_slacpy                                   LACPY
#define CHAMELEON_DAG_TASK_COLOR_NAME_slacpyx                                  LACPY
#define CHAMELEON_DAG_TASK_COLOR_NAME_slag2c                                   LAG2C
#define CHAMELEON_DAG_TASK_COLOR_NAME_slag2d                                   LAG2D
#define CHAMELEON_DAG_TASK_COLOR_NAME_slag2h                                   LAG2H
#define CHAMELEON_DAG_TASK_COLOR_NAME_slange                                   LANGE
#define CHAMELEON_DAG_TASK_COLOR_NAME_slange_max                               LANGE_MAX
#define CHAMELEON_DAG_TASK_COLOR_NAME_slascal                                  LASCAL
#define CHAMELEON_DAG_TASK_COLOR_NAME_slaset                                   LASET
#define CHAMELEON_DAG_TASK_COLOR_NAME_slaset2                                  LASET
#define CHAMELEON_DAG_TASK_COLOR_NAME_slaswp_batched                           LASWP
#define CHAMELEON_DAG_TASK_COLOR_NAME_slaswp_gemm                              LASWP
#define CHAMELEON_DAG_TASK_COLOR_NAME_slaswp_get                               LASWP
#define CHAMELEON_DAG_TASK_COLOR_NAME_slaswp_get_batched                       LASWP
#define CHAMELEON_DAG_TASK_COLOR_NAME_slaswp_ret                               LASWP
#define CHAMELEON_DAG_TASK_COLOR_NAME_slaswp_set                               LASWP
#define CHAMELEON_DAG_TASK_COLOR_NAME_slaswp_set_batched                       LASWP
#define CHAMELEON_DAG_TASK_COLOR_NAME_slatro                                   LATRO
#define CHAMELEON_DAG_TASK_COLOR_NAME_slauum                                   LAUUM
#define CHAMELEON_DAG_TASK_COLOR_NAME_slumm                                    LUMM
#define CHAMELEON_DAG_TASK_COLOR_NAME_sormlq                                   ORMLQ
#define CHAMELEON_DAG_TASK_COLOR_NAME_sormqr                                   ORMQR
#define CHAMELEON_DAG_TASK_COLOR_NAME_sperm_allreduce                          PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_sperm_allreduce_col                      PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_sperm_allreduce_init                     PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_sperm_allreduce_send_col                 PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_sperm_reduce                             PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_sperm_reduce_col                         PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_sperm_reduce_col_send                    PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_sperm_reduce_init                        PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_sperm_reduce_send                        PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_spivot_allreduce                         PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_spivot_allreduce_recv                    PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_spivot_allreduce_send                    PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_splgsy                                   PLGSY
#define CHAMELEON_DAG_TASK_COLOR_NAME_splrnt                                   PLRNT
#define CHAMELEON_DAG_TASK_COLOR_NAME_splssq                                   PLSSQ
#define CHAMELEON_DAG_TASK_COLOR_NAME_splssq2                                  PLSSQ2
#define CHAMELEON_DAG_TASK_COLOR_NAME_spotrf                                   POTRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_sset_reciprocal_diagonal                 SET_RECIPROCAL_DIAGONAL
#define CHAMELEON_DAG_TASK_COLOR_NAME_sssssm                                   SSSSM
#define CHAMELEON_DAG_TASK_COLOR_NAME_ssymm                                    SYMM
#define CHAMELEON_DAG_TASK_COLOR_NAME_ssyr2k                                   SYR2K
#define CHAMELEON_DAG_TASK_COLOR_NAME_ssyrfb                                   SYRFB
#define CHAMELEON_DAG_TASK_COLOR_NAME_ssyrk                                    SYRK
#define CHAMELEON_DAG_TASK_COLOR_NAME_ssytrrk                                  SYTRRK
#define CHAMELEON_DAG_TASK_COLOR_NAME_stplqt                                   TPLQT
#define CHAMELEON_DAG_TASK_COLOR_NAME_stpmlqt                                  TPMLQT
#define CHAMELEON_DAG_TASK_COLOR_NAME_stpmqrt                                  TPMQRT
#define CHAMELEON_DAG_TASK_COLOR_NAME_stpqrt                                   TPQRT
#define CHAMELEON_DAG_TASK_COLOR_NAME_stradd                                   TRADD
#define CHAMELEON_DAG_TASK_COLOR_NAME_strasm                                   TRASM
#define CHAMELEON_DAG_TASK_COLOR_NAME_strmm                                    TRMM
#define CHAMELEON_DAG_TASK_COLOR_NAME_strmmoop                                 TRMM
#define CHAMELEON_DAG_TASK_COLOR_NAME_strsm                                    TRSM
#define CHAMELEON_DAG_TASK_COLOR_NAME_strtri                                   TRTRI
#define CHAMELEON_DAG_TASK_COLOR_NAME_strtrmm                                  TRTRMM
#define CHAMELEON_DAG_TASK_COLOR_NAME_strtrsm                                  TRTRSM
#define CHAMELEON_DAG_TASK_COLOR_NAME_stsmlq_hetra1                            TSMLQ
#define CHAMELEON_DAG_TASK_COLOR_NAME_stsmqr_hetra1                            TSMQR
#define CHAMELEON_DAG_TASK_COLOR_NAME_ststrf                                   TSTRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_zaddi                                    ADDI
#define CHAMELEON_DAG_TASK_COLOR_NAME_zaxpy                                    AXPY
#define CHAMELEON_DAG_TASK_COLOR_NAME_zcesca                                   CESCA
#define CHAMELEON_DAG_TASK_COLOR_NAME_zgeadd                                   GEADD
#define CHAMELEON_DAG_TASK_COLOR_NAME_zgelqt                                   GELQT
#define CHAMELEON_DAG_TASK_COLOR_NAME_zgemm                                    GEMM
#define CHAMELEON_DAG_TASK_COLOR_NAME_zgemv                                    GEMV
#define CHAMELEON_DAG_TASK_COLOR_NAME_zgeqrt                                   GEQRT
#define CHAMELEON_DAG_TASK_COLOR_NAME_zgessm                                   GESSM
#define CHAMELEON_DAG_TASK_COLOR_NAME_zgessq                                   GESSQ
#define CHAMELEON_DAG_TASK_COLOR_NAME_zgesum                                   GESUM
#define CHAMELEON_DAG_TASK_COLOR_NAME_zgetrf                                   GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_zgetrf_blocked_diag                      GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_zgetrf_blocked_offdiag                   GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_zgetrf_blocked_trsm                      GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_zgetrf_cpy_pivrow_in_Up                  GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_zgetrf_incpiv                            GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_zgetrf_nopiv                             GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_cgetrf_nopiv_panel_facto                 GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_dgetrf_nopiv_panel_facto                 GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_sgetrf_nopiv_panel_facto                 GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_zgetrf_nopiv_panel_facto                 GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_cgetrf_nopiv_panel_update                GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_dgetrf_nopiv_panel_update                GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_sgetrf_nopiv_panel_update                GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_zgetrf_nopiv_panel_update                GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_zgetrf_nopiv_percol_diag                 GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_zgetrf_nopiv_percol_trsm                 GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_zgetrf_panel_blocked_batched             GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_zgetrf_panel_offdiag_batched             GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_zgetrf_panel_percol_offdiag_batched      GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_zgetrf_percol_diag                       GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_zgetrf_percol_offdiag                    GETRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_zgram                                    GRAM
#define CHAMELEON_DAG_TASK_COLOR_NAME_zhe2ge                                   HE2GE
#define CHAMELEON_DAG_TASK_COLOR_NAME_zhemm                                    HEMM
#define CHAMELEON_DAG_TASK_COLOR_NAME_zher2k                                   HER2K
#define CHAMELEON_DAG_TASK_COLOR_NAME_zherfb                                   HERFB
#define CHAMELEON_DAG_TASK_COLOR_NAME_zherk                                    HERK
#define CHAMELEON_DAG_TASK_COLOR_NAME_zhetrrk                                  HETRRK
#define CHAMELEON_DAG_TASK_COLOR_NAME_zipiv_allreduce                          PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_zipiv_allreduce_recv                     PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_zipiv_allreduce_send                     PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_zlacpy                                   LACPY
#define CHAMELEON_DAG_TASK_COLOR_NAME_zlacpyx                                  LACPY
#define CHAMELEON_DAG_TASK_COLOR_NAME_zlag2c                                   LAG2C
#define CHAMELEON_DAG_TASK_COLOR_NAME_zlange                                   LANGE
#define CHAMELEON_DAG_TASK_COLOR_NAME_zlange_max                               LANGE_MAX
#define CHAMELEON_DAG_TASK_COLOR_NAME_zlascal                                  LASCAL
#define CHAMELEON_DAG_TASK_COLOR_NAME_zlaset                                   LASET
#define CHAMELEON_DAG_TASK_COLOR_NAME_zlaset2                                  LASET
#define CHAMELEON_DAG_TASK_COLOR_NAME_zlaswp_batched                           LASWP
#define CHAMELEON_DAG_TASK_COLOR_NAME_zlaswp_gemm                              LASWP
#define CHAMELEON_DAG_TASK_COLOR_NAME_zlaswp_get                               LASWP
#define CHAMELEON_DAG_TASK_COLOR_NAME_zlaswp_get_batched                       LASWP
#define CHAMELEON_DAG_TASK_COLOR_NAME_zlaswp_ret                               LASWP
#define CHAMELEON_DAG_TASK_COLOR_NAME_zlaswp_set                               LASWP
#define CHAMELEON_DAG_TASK_COLOR_NAME_zlaswp_set_batched                       LASWP
#define CHAMELEON_DAG_TASK_COLOR_NAME_zlatro                                   LATRO
#define CHAMELEON_DAG_TASK_COLOR_NAME_zlauum                                   LAUUM
#define CHAMELEON_DAG_TASK_COLOR_NAME_zlumm                                    LUMM
#define CHAMELEON_DAG_TASK_COLOR_NAME_zperm_allreduce                          PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_zperm_allreduce_col                      PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_zperm_allreduce_init                     PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_zperm_allreduce_send_col                 PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_zperm_reduce                             PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_zperm_reduce_col                         PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_zperm_reduce_col_send                    PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_zperm_reduce_init                        PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_zperm_reduce_send                        PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_zpivot_allreduce                         PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_zpivot_allreduce_recv                    PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_zpivot_allreduce_send                    PERM
#define CHAMELEON_DAG_TASK_COLOR_NAME_zplghe                                   PLGHE
#define CHAMELEON_DAG_TASK_COLOR_NAME_zplgsy                                   PLGSY
#define CHAMELEON_DAG_TASK_COLOR_NAME_zplrnt                                   PLRNT
#define CHAMELEON_DAG_TASK_COLOR_NAME_zplssq                                   PLSSQ
#define CHAMELEON_DAG_TASK_COLOR_NAME_zplssq2                                  PLSSQ2
#define CHAMELEON_DAG_TASK_COLOR_NAME_zpotrf                                   POTRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_zset_reciprocal_diagonal                 SET_RECIPROCAL_DIAGONAL
#define CHAMELEON_DAG_TASK_COLOR_NAME_zssssm                                   SSSSM
#define CHAMELEON_DAG_TASK_COLOR_NAME_zsymm                                    SYMM
#define CHAMELEON_DAG_TASK_COLOR_NAME_zsyr2k                                   SYR2K
#define CHAMELEON_DAG_TASK_COLOR_NAME_zsyrk                                    SYRK
#define CHAMELEON_DAG_TASK_COLOR_NAME_zsytrf_nopiv                             SYTRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_zsytrrk                                  SYTRRK
#define CHAMELEON_DAG_TASK_COLOR_NAME_ztplqt                                   TPLQT
#define CHAMELEON_DAG_TASK_COLOR_NAME_ztpmlqt                                  TPMLQT
#define CHAMELEON_DAG_TASK_COLOR_NAME_ztpmqrt                                  TPMQRT
#define CHAMELEON_DAG_TASK_COLOR_NAME_ztpqrt                                   TPQRT
#define CHAMELEON_DAG_TASK_COLOR_NAME_ztradd                                   TRADD
#define CHAMELEON_DAG_TASK_COLOR_NAME_ztrasm                                   TRASM
#define CHAMELEON_DAG_TASK_COLOR_NAME_ztrmm                                    TRMM
#define CHAMELEON_DAG_TASK_COLOR_NAME_ztrmmoop                                 TRMM
#define CHAMELEON_DAG_TASK_COLOR_NAME_ztrsm                                    TRSM
#define CHAMELEON_DAG_TASK_COLOR_NAME_ztrtri                                   TRTRI
#define CHAMELEON_DAG_TASK_COLOR_NAME_ztrtrmm                                  TRTRMM
#define CHAMELEON_DAG_TASK_COLOR_NAME_ztrtrsm                                  TRTRSM
#define CHAMELEON_DAG_TASK_COLOR_NAME_ztsmlq_hetra1                            TSMLQ
#define CHAMELEON_DAG_TASK_COLOR_NAME_ztsmqr_hetra1                            TSMQR
#define CHAMELEON_DAG_TASK_COLOR_NAME_ztstrf                                   TSTRF
#define CHAMELEON_DAG_TASK_COLOR_NAME_zunmlq                                   UNMLQ
#define CHAMELEON_DAG_TASK_COLOR_NAME_zunmqr                                   UNMQR

/* Associate each precision-neutral task class with one palette family. */
#define CHAMELEON_DAG_TASK_COLOR_ADDI                           CHAMELEON_DAG_COLOR_BLAS1
#define CHAMELEON_DAG_TASK_COLOR_LAG2D                          CHAMELEON_DAG_COLOR_COPY
#define CHAMELEON_DAG_TASK_COLOR_LAG2S                          CHAMELEON_DAG_COLOR_COPY
#define CHAMELEON_DAG_TASK_COLOR_LUMM                           CHAMELEON_DAG_COLOR_LU
#define CHAMELEON_DAG_TASK_COLOR_HETRRK                         CHAMELEON_DAG_COLOR_LU
#define CHAMELEON_DAG_TASK_COLOR_SYTRRK                         CHAMELEON_DAG_COLOR_LU
#define CHAMELEON_DAG_TASK_COLOR_SYRFB                          CHAMELEON_DAG_COLOR_LU
#define CHAMELEON_DAG_TASK_COLOR_SET_RECIPROCAL_DIAGONAL        CHAMELEON_DAG_COLOR_MISC
#define CHAMELEON_DAG_TASK_COLOR_TRTRMM                         CHAMELEON_DAG_COLOR_TRMM
#define CHAMELEON_DAG_TASK_COLOR_TRTRSM                         CHAMELEON_DAG_COLOR_TRSM
#define CHAMELEON_DAG_TASK_COLOR_ASUM                           CHAMELEON_DAG_COLOR_BLAS1
#define CHAMELEON_DAG_TASK_COLOR_AXPY                           CHAMELEON_DAG_COLOR_BLAS1
#define CHAMELEON_DAG_TASK_COLOR_BUILD                          CHAMELEON_DAG_COLOR_MISC
#define CHAMELEON_DAG_TASK_COLOR_CONVERT                        CHAMELEON_DAG_COLOR_MISC
#define CHAMELEON_DAG_TASK_COLOR_MAP                            CHAMELEON_DAG_COLOR_MISC
#define CHAMELEON_DAG_TASK_COLOR_GEADD                          CHAMELEON_DAG_COLOR_BLAS1
#define CHAMELEON_DAG_TASK_COLOR_GESUM                          CHAMELEON_DAG_COLOR_BLAS1
#define CHAMELEON_DAG_TASK_COLOR_LASCAL                         CHAMELEON_DAG_COLOR_BLAS1
#define CHAMELEON_DAG_TASK_COLOR_TRADD                          CHAMELEON_DAG_COLOR_BLAS1
#define CHAMELEON_DAG_TASK_COLOR_GEMV                           CHAMELEON_DAG_COLOR_BLAS2
#define CHAMELEON_DAG_TASK_COLOR_GEMM                           CHAMELEON_DAG_COLOR_GEMM
#define CHAMELEON_DAG_TASK_COLOR_HEMM                           CHAMELEON_DAG_COLOR_HEMM
#define CHAMELEON_DAG_TASK_COLOR_SYMM                           CHAMELEON_DAG_COLOR_SYMM
#define CHAMELEON_DAG_TASK_COLOR_HER2K                          CHAMELEON_DAG_COLOR_HER2K
#define CHAMELEON_DAG_TASK_COLOR_HERK                           CHAMELEON_DAG_COLOR_HERK
#define CHAMELEON_DAG_TASK_COLOR_SYR2K                          CHAMELEON_DAG_COLOR_SYR2K
#define CHAMELEON_DAG_TASK_COLOR_SYRK                           CHAMELEON_DAG_COLOR_SYRK
#define CHAMELEON_DAG_TASK_COLOR_TRMM                           CHAMELEON_DAG_COLOR_TRMM
#define CHAMELEON_DAG_TASK_COLOR_TRSM                           CHAMELEON_DAG_COLOR_TRSM
#define CHAMELEON_DAG_TASK_COLOR_GELQT                          CHAMELEON_DAG_COLOR_QR
#define CHAMELEON_DAG_TASK_COLOR_GEQRT                          CHAMELEON_DAG_COLOR_QR
#define CHAMELEON_DAG_TASK_COLOR_TPLQT                          CHAMELEON_DAG_COLOR_QR
#define CHAMELEON_DAG_TASK_COLOR_TPQRT                          CHAMELEON_DAG_COLOR_QR
#define CHAMELEON_DAG_TASK_COLOR_TSTRF                          CHAMELEON_DAG_COLOR_QR
#define CHAMELEON_DAG_TASK_COLOR_TPMLQT                         CHAMELEON_DAG_COLOR_APPLYQ
#define CHAMELEON_DAG_TASK_COLOR_TPMQRT                         CHAMELEON_DAG_COLOR_APPLYQ
#define CHAMELEON_DAG_TASK_COLOR_TSMLQ                          CHAMELEON_DAG_COLOR_APPLYQ
#define CHAMELEON_DAG_TASK_COLOR_TSMQR                          CHAMELEON_DAG_COLOR_APPLYQ
#define CHAMELEON_DAG_TASK_COLOR_UNMLQ                          CHAMELEON_DAG_COLOR_APPLYQ
#define CHAMELEON_DAG_TASK_COLOR_UNMQR                          CHAMELEON_DAG_COLOR_APPLYQ
#define CHAMELEON_DAG_TASK_COLOR_ORMLQ                          CHAMELEON_DAG_COLOR_APPLYQ
#define CHAMELEON_DAG_TASK_COLOR_ORMQR                          CHAMELEON_DAG_COLOR_APPLYQ
#define CHAMELEON_DAG_TASK_COLOR_GESSM                          CHAMELEON_DAG_COLOR_LU
#define CHAMELEON_DAG_TASK_COLOR_GETRF                          CHAMELEON_DAG_COLOR_LU
#define CHAMELEON_DAG_TASK_COLOR_SSSSM                          CHAMELEON_DAG_COLOR_LU
#define CHAMELEON_DAG_TASK_COLOR_SYTRF                          CHAMELEON_DAG_COLOR_LU
#define CHAMELEON_DAG_TASK_COLOR_POTRF                          CHAMELEON_DAG_COLOR_FACTO
#define CHAMELEON_DAG_TASK_COLOR_LAUUM                          CHAMELEON_DAG_COLOR_FACTO
#define CHAMELEON_DAG_TASK_COLOR_TRTRI                          CHAMELEON_DAG_COLOR_FACTO
#define CHAMELEON_DAG_TASK_COLOR_HERFB                          CHAMELEON_DAG_COLOR_BAND
#define CHAMELEON_DAG_TASK_COLOR_TRASM                          CHAMELEON_DAG_COLOR_BAND
#define CHAMELEON_DAG_TASK_COLOR_LACPY                          CHAMELEON_DAG_COLOR_COPY
#define CHAMELEON_DAG_TASK_COLOR_LAG2C                          CHAMELEON_DAG_COLOR_COPY
#define CHAMELEON_DAG_TASK_COLOR_LAG2H                          CHAMELEON_DAG_COLOR_COPY
#define CHAMELEON_DAG_TASK_COLOR_LAG2Z                          CHAMELEON_DAG_COLOR_COPY
#define CHAMELEON_DAG_TASK_COLOR_LATRO                          CHAMELEON_DAG_COLOR_COPY
#define CHAMELEON_DAG_TASK_COLOR_LASET                          CHAMELEON_DAG_COLOR_COPY
#define CHAMELEON_DAG_TASK_COLOR_HE2GE                          CHAMELEON_DAG_COLOR_COPY
#define CHAMELEON_DAG_TASK_COLOR_GETRIP                         CHAMELEON_DAG_COLOR_MISC
#define CHAMELEON_DAG_TASK_COLOR_SHIFT                          CHAMELEON_DAG_COLOR_MISC
#define CHAMELEON_DAG_TASK_COLOR_SHIFTW                         CHAMELEON_DAG_COLOR_MISC
#define CHAMELEON_DAG_TASK_COLOR_LANGE                          CHAMELEON_DAG_COLOR_NORM
#define CHAMELEON_DAG_TASK_COLOR_LANGE_MAX                      CHAMELEON_DAG_COLOR_NORM
#define CHAMELEON_DAG_TASK_COLOR_LANHE                          CHAMELEON_DAG_COLOR_NORM
#define CHAMELEON_DAG_TASK_COLOR_LANSY                          CHAMELEON_DAG_COLOR_NORM
#define CHAMELEON_DAG_TASK_COLOR_LANTR                          CHAMELEON_DAG_COLOR_NORM
#define CHAMELEON_DAG_TASK_COLOR_LASSQ                          CHAMELEON_DAG_COLOR_NORM
#define CHAMELEON_DAG_TASK_COLOR_GESSQ                          CHAMELEON_DAG_COLOR_NORM
#define CHAMELEON_DAG_TASK_COLOR_HESSQ                          CHAMELEON_DAG_COLOR_NORM
#define CHAMELEON_DAG_TASK_COLOR_SYSSQ                          CHAMELEON_DAG_COLOR_NORM
#define CHAMELEON_DAG_TASK_COLOR_TRSSQ                          CHAMELEON_DAG_COLOR_NORM
#define CHAMELEON_DAG_TASK_COLOR_PLSSQ                          CHAMELEON_DAG_COLOR_NORM
#define CHAMELEON_DAG_TASK_COLOR_PLSSQ2                         CHAMELEON_DAG_COLOR_NORM
#define CHAMELEON_DAG_TASK_COLOR_LASWP                          CHAMELEON_DAG_COLOR_PERM
#define CHAMELEON_DAG_TASK_COLOR_SWPAB                          CHAMELEON_DAG_COLOR_PERM
#define CHAMELEON_DAG_TASK_COLOR_PERM                           CHAMELEON_DAG_COLOR_PERM
#define CHAMELEON_DAG_TASK_COLOR_CESCA                          CHAMELEON_DAG_COLOR_ANALYSIS
#define CHAMELEON_DAG_TASK_COLOR_GRAM                           CHAMELEON_DAG_COLOR_ANALYSIS
#define CHAMELEON_DAG_TASK_COLOR_PLGHE                          CHAMELEON_DAG_COLOR_RANDOM
#define CHAMELEON_DAG_TASK_COLOR_PLGSY                          CHAMELEON_DAG_COLOR_RANDOM
#define CHAMELEON_DAG_TASK_COLOR_PLRNT                          CHAMELEON_DAG_COLOR_RANDOM

#endif /* _chameleon_dag_task_colors_h_ */
